name: Generate AI Hype Graph

on:
  push:
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytrends matplotlib
          
      - name: Generate Graph
        run: python generate-graph.py 
        
      -
